parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: drh
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8652192d611f9ad37deaa42f99456705
    database_path: null
